// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPQjns4uXgBoawZ09rG6LuJecH_WlZ6xk',
    appId: '1:146434390408:web:2471c79d70ec357d60e23d',
    messagingSenderId: '146434390408',
    projectId: 'test-ba07b',
    authDomain: 'test-ba07b.firebaseapp.com',
    storageBucket: 'test-ba07b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6HNxDaoU-9ZXNl0QOLa8JWjlZYuJGRTE',
    appId: '1:146434390408:android:5a0ed749ab4484de60e23d',
    messagingSenderId: '146434390408',
    projectId: 'test-ba07b',
    storageBucket: 'test-ba07b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiHyccMqr7perN9TdEOp8rwZXiYlr5IGM',
    appId: '1:146434390408:ios:bbb71647d6e7bdd360e23d',
    messagingSenderId: '146434390408',
    projectId: 'test-ba07b',
    storageBucket: 'test-ba07b.appspot.com',
    iosClientId: '146434390408-886rhv36mlk1ckg6qlrbv0ege06bf2r2.apps.googleusercontent.com',
    iosBundleId: 'com.example.acakSoal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiHyccMqr7perN9TdEOp8rwZXiYlr5IGM',
    appId: '1:146434390408:ios:bbb71647d6e7bdd360e23d',
    messagingSenderId: '146434390408',
    projectId: 'test-ba07b',
    storageBucket: 'test-ba07b.appspot.com',
    iosClientId: '146434390408-886rhv36mlk1ckg6qlrbv0ege06bf2r2.apps.googleusercontent.com',
    iosBundleId: 'com.example.acakSoal',
  );
}
